version: "3"

services:
  app:
    build: .
    ports:
      - 8501:8501
    stdin_open: true
    image: au-ventures
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./src:/app/src/