name: merge

on:
  push:
    branches:
      - main
jobs:

  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    needs: [lint]
    uses: ./.github/workflows/test.yaml

  build_docker:
    needs: [lint, test]
    uses: ./.github/workflows/docker-build.yaml
    with:
      image_branch_tag: 'latest'
      image_sha_tag: ${{ github.sha }}