name: merge

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-west-2
  DEBUG: false

jobs:

  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    needs: [lint]
    uses: ./.github/workflows/test.yaml

  build_docker:
    needs: [lint, test]
    uses: ./.github/workflows/docker-build.yaml
    with:
      ENVIRONMENT: dev
      image_branch_tag: 'latest'
    secrets:
      token: ${{ secrets.TOKEN }}
