name: test

on:
  workflow_call:

jobs:
  test_python:
    runs-on: ubuntu-latest

    steps:
      - name: system-deps
        run: |
          sudo apt-get update

      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: load pip cache
        uses: actions/cache@v3
        timeout-minutes: 5
        continue-on-error: true
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: install pip deps
        run: make install

      - name: run python lint
        run: make test
